In [89]:
import xarray as xr

In [94]:
import numpy as np

import metpy.calc as mpcalc
from metpy.interpolate import cross_section

In [104]:
test_again = xr.open_dataset("/Users/nicolema/Downloads/hrrr.t00z.wrfnatf00.grib2",engine='cfgrib',backend_kwargs=dict(filter_by_keys={'typeOfLevel': 'hybrid'}))

In [109]:
cf_attrs = {
    'grid_mapping_name': 'lambert_conformal_conic',
    'standard_parallel': 38.5,
    'longitude_of_central_meridian': -97.5,
    'latitude_of_projection_origin': 38.5,
    'earth_radius': 6371229.0
}
ds = test_again.metpy.assign_crs(cf_attrs).metpy.assign_y_x()
ds



/var/folders/7f/t57b14s52j146xdgkwf7mn840000gn/T/ipykernel_39631/3844753131.py:8: UserWarning: More than one time coordinate present for variable  "pres".
  ds = test_again.metpy.assign_crs(cf_attrs).metpy.assign_y_x()
/var/folders/7f/t57b14s52j146xdgkwf7mn840000gn/T/ipykernel_39631/3844753131.py:8: UserWarning: More than one time coordinate present for variable  "clwmr".
  ds = test_again.metpy.assign_crs(cf_attrs).metpy.assign_y_x()
/var/folders/7f/t57b14s52j146xdgkwf7mn840000gn/T/ipykernel_39631/3844753131.py:8: UserWarning: More than one time coordinate present for variable  "unknown".
  ds = test_again.metpy.assign_crs(cf_attrs).metpy.assign_y_x()
/var/folders/7f/t57b14s52j146xdgkwf7mn840000gn/T/ipykernel_39631/3844753131.py:8: UserWarning: More than one time coordinate present for variable  "rwmr".
  ds = test_again.metpy.assign_crs(cf_attrs).metpy.assign_y_x()
/var/folders/7f/t57b14s52j146xdgkwf7mn840000gn/T/ipykernel_39631/3844753131.py:8: UserWarning: More than one time coordi

<xarray.Dataset>
Dimensions:     (hybrid: 50, y: 1059, x: 1799)
Coordinates:
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
  * hybrid      (hybrid) float64 1.0 2.0 3.0 4.0 5.0 ... 47.0 48.0 49.0 50.0
    latitude    (y, x) float64 21.14 21.15 21.15 21.16 ... 47.86 47.85 47.84
    longitude   (y, x) float64 237.3 237.3 237.3 237.4 ... 299.0 299.0 299.1
    valid_time  datetime64[ns] ...
    metpy_crs   object Projection: lambert_conformal_conic
  * y           (y) float64 -1.587e+06 -1.584e+06 ... 1.584e+06 1.587e+06
  * x           (x) float64 -2.698e+06 -2.695e+06 ... 2.693e+06 2.696e+06
Data variables: (12/17)
    pres        (hybrid, y, x) float32 ...
    clwmr       (hybrid, y, x) float32 ...
    unknown     (hybrid, y, x) float32 ...
    rwmr        (hybrid, y, x) float32 ...
    snmr        (hybrid, y, x) float32 ...
    grle        (hybrid, y, x) float32 ...
    ...          ...
    q           (hybrid, y, x) float32 ...
    u           (hybrid, y, x) float32 ...
    v           (hybrid, y, x) float32 ...
    w           (hybrid, y, x) float32 ...
    tke         (hybrid, y, x) float32 ...
    mdens       (hybrid, y, x) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2024-07-23T09:14 GRIB to CDM+CF via cfgrib-0.9.1...

In [116]:
point_lon = -72.717
point_lat = 39.969 

projection = ccrs.LambertConformal(central_longitude=262.5, 
                                   central_latitude=38.5, 
                                   standard_parallels=(38.5, 38.5),
                                    globe=ccrs.Globe(semimajor_axis=6371229,
                                                     semiminor_axis=6371229))

x, y = projection.transform_point(point_lon, point_lat, ccrs.PlateCarree())

# longitude is x, latitude is y

In [120]:
ds_2 = ds.sel(y=y,x=x,method='nearest')

In [125]:
ds_3 = ds_2.drop_vars(['clwmr','unknown','rwmr','snmr','grle'])

In [126]:
ds_3

<xarray.Dataset>
Dimensions:     (hybrid: 50)
Coordinates:
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
  * hybrid      (hybrid) float64 1.0 2.0 3.0 4.0 5.0 ... 47.0 48.0 49.0 50.0
    latitude    float64 39.97
    longitude   float64 287.3
    valid_time  datetime64[ns] ...
    metpy_crs   object Projection: lambert_conformal_conic
    y           float64 4.467e+05
    x           float64 2.087e+06
Data variables:
    pres        (hybrid) float32 1.021e+05 1.018e+05 ... 2.209e+03 1.731e+03
    pmtf        (hybrid) float32 5.63e+10 2.95e+10 2e+09 ... 5.981e+08 5.742e+08
    pmtc        (hybrid) float32 1.43e+06 1.66e+06 1.94e+06 ... 0.0 10.0 90.0
    cc          (hybrid) float32 0.04 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    gh          (hybrid) float32 10.38 38.65 88.25 ... 2.598e+04 2.761e+04
    t           (hybrid) float32 286.1 289.0 289.1 288.7 ... 221.3 223.4 225.5
    q           (hybrid) float32 0.0053 0.00282 0.00284 ... 2.898e-06 2.947e-06
    u           (hybrid) float32 1.202 1.847 2.452 ... -1.684 -2.433 -2.441
    v           (hybrid) float32 2.95 3.871 3.659 ... -0.04911 -0.8926 -1.411
    w           (hybrid) float32 -0.009075 -0.00946 ... -1.486e-07 -1.149e-08
    tke         (hybrid) float32 5e-05 5e-05 5e-05 5e-05 ... 5e-05 5e-05 5e-05
    mdens       (hybrid) float32 1.044e-16 1.04e-16 ... 1.453e-10 2.526e-11
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2024-07-23T09:14 GRIB to CDM+CF via cfgrib-0.9.1...

In [71]:
# point_lon = -72.717
# point_lat = 39.969 

# projection = ccrs.LambertConformal(central_longitude=262.5, 
#                                    central_latitude=38.5, 
#                                    standard_parallels=(38.5, 38.5),
#                                     globe=ccrs.Globe(semimajor_axis=6371229,
#                                                      semiminor_axis=6371229))

# x, y = projection.transform_point(point_lon, point_lat, ccrs.PlateCarree())

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr

import warnings

import herbie
from herbie import Herbie, FastHerbie

In [2]:
import metpy.calc
from metpy.units import units

In [3]:
import numpy as np

In [4]:
test = xr.open_dataset("/Volumes/hrrr/full/20190501.t00z.wrfprsf00.grib2",engine='cfgrib',backend_kwargs=dict(filter_by_keys={'typeOfLevel': 'isobaricInhPa'}))

In [5]:
test_2 = test.drop_vars(['unknown'])

In [6]:
ws = np.sqrt(np.add(test_2.u.to_numpy() ** 2,test_2.v.to_numpy()** 2))

In [7]:
ws_xr = xr.DataArray(ws)

In [8]:
test_2['ws'] = ws_xr

In [9]:
test_2

<xarray.Dataset>
Dimensions:        (isobaricInhPa: 40, y: 1059, x: 1799, dim_0: 40,
                    dim_1: 1059, dim_2: 1799)
Coordinates:
    time           datetime64[ns] ...
    step           timedelta64[ns] ...
  * isobaricInhPa  (isobaricInhPa) float64 1.013e+03 1e+03 975.0 ... 75.0 50.0
    latitude       (y, x) float64 ...
    longitude      (y, x) float64 ...
    valid_time     datetime64[ns] ...
Dimensions without coordinates: y, x, dim_0, dim_1, dim_2
Data variables: (12/14)
    gh             (isobaricInhPa, y, x) float32 ...
    t              (isobaricInhPa, y, x) float32 ...
    r              (isobaricInhPa, y, x) float32 ...
    dpt            (isobaricInhPa, y, x) float32 ...
    q              (isobaricInhPa, y, x) float32 ...
    w              (isobaricInhPa, y, x) float32 ...
    ...             ...
    absv           (isobaricInhPa, y, x) float32 ...
    clwmr          (isobaricInhPa, y, x) float32 ...
    rwmr           (isobaricInhPa, y, x) float32 ...
    snmr           (isobaricInhPa, y, x) float32 ...
    grle           (isobaricInhPa, y, x) float32 ...
    ws             (dim_0, dim_1, dim_2) float32 5.254 5.254 5.2 ... 5.991 5.968
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2024-07-22T10:49 GRIB to CDM+CF via cfgrib-0.9.1...

In [119]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr

import warnings

import herbie
from herbie import Herbie, FastHerbie

In [122]:
slc = test_2.herbie.pick_points(
    pd.DataFrame({"latitude": [40.76], "longitude": [-111.876183]})
)

AttributeError: 'HerbieAccessor' object has no attribute 'pick_points'

In [10]:
projection = ccrs.LambertConformal(
    central_longitude = -97.5,
    central_latitude = 38.5,
    standard_parallels = (38.5,38.5),
    cutoff = 0)

NameError: name 'ccrs' is not defined

In [ ]:
list(test_2.coords['latitude'].to_numpy())

[array([21.138123  , 21.14511004, 21.1520901 , ..., 21.1545089 ,
        21.14753125, 21.14054663]),
 array([21.16299459, 21.1699845 , 21.17696744, ..., 21.17938723,
        21.1724067 , 21.16541921]),
 array([21.18786863, 21.19486142, 21.20184723, ..., 21.20426802,
        21.19728462, 21.19029425]),
 array([21.21274513, 21.21974079, 21.22672948, ..., 21.22915126,
        21.22216499, 21.21517175]),
 array([21.23762407, 21.24462262, 21.25161418, ..., 21.25403696,
        21.24704782, 21.24005169]),
 array([21.26250547, 21.26950689, 21.27650133, ..., 21.2789251 ,
        21.27193308, 21.26493408]),
 array([21.2873893 , 21.2943936 , 21.30139092, ..., 21.30381569,
        21.29682079, 21.28981891]),
 array([21.31227557, 21.31928275, 21.32628295, ..., 21.32870871,
        21.32171094, 21.31470618]),
 array([21.33716427, 21.34417434, 21.35117741, ..., 21.35360417,
        21.34660353, 21.33959589]),
 array([21.36205541, 21.36906835, 21.3760743 , ..., 21.37850206,
        21.37149854, 21.36

In [22]:
print(test_again)

<xarray.Dataset>
Dimensions:     (hybrid: 50, y: 1059, x: 1799)
Coordinates:
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
  * hybrid      (hybrid) float64 1.0 2.0 3.0 4.0 5.0 ... 47.0 48.0 49.0 50.0
    latitude    (y, x) float64 ...
    longitude   (y, x) float64 ...
    valid_time  datetime64[ns] ...
Dimensions without coordinates: y, x
Data variables: (12/17)
    pres        (hybrid, y, x) float32 ...
    clwmr       (hybrid, y, x) float32 ...
    unknown     (hybrid, y, x) float32 ...
    rwmr        (hybrid, y, x) float32 ...
    snmr        (hybrid, y, x) float32 ...
    grle        (hybrid, y, x) float32 ...
    ...          ...
    q           (hybrid, y, x) float32 ...
    u           (hybrid, y, x) float32 ...
    v           (hybrid, y, x) float32 ...
    w           (hybrid, y, x) float32 ...
    tke         (hybrid, y, x) float32 ...
    mdens       (hybrid, y, x) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             

In [44]:
import metpy.calc as mpcalc
from metpy.units import units
import numpy as np

press = np.array([950]) * units.hPa
metpy.calc.pressure_to_height_std(press)

# [1013., 1000.,  975.,  950.,  925.,  900.,  875.,  850.,  825.,  800.,
# 775.,  750.,  725.,  700.,  675.,  650.,  625.,  600.,  575.,  550.,
# 525.,  500.,  475.,  450.,  425.,  400.,  375.,  350.,  325.,  300.,
# 275.,  250.,  225.,  200.,  175.,  150.,  125.,  100.,   75.,   50.]

array([0.323207]) <Unit('kilometer')>

## get point

In [122]:
import s3fs
import numcodecs as ncd
import numpy as np
import datetime
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

fs = s3fs.S3FileSystem(anon=True)

In [40]:
point_lat = 39.969
point_lon = -72.717

date = '20190901' #YYYYMMDD

hr = '00' #[00-23]z must be in the two digit format

level = '975mb' 
# [1013., 1000.,  975.,  950.,  925.,  900.,  875.,  850.,  825.,  800.,
# 775.,  750.,  725.,  700.,  675.,  650.,  625.,  600.,  575.,  550.,
# 525.,  500.,  475.,  450.,  425.,  400.,  375.,  350.,  325.,  300.,
# 275.,  250.,  225.,  200.,  175.,  150.,  125.,  100.,   75.,   50.]


var_u = 'UGRD'
var_v = 'VGRD'
var_ght = 'HGT'
var_t = 'TMP'

var = var_ght

data_url = f'hrrrzarr/sfc/{date}/{date}_{hr}z_fcst.zarr/{level}/{var}/{level}/{var}/'

In [41]:
chunk_index = xr.open_zarr(s3fs.S3Map("s3://hrrrzarr/grid/HRRR_chunk_index.zarr", s3=fs))

In [78]:
import cartopy.crs as ccrs

# This is the projection the HRRR grid uses.
projection = ccrs.LambertConformal(central_longitude=262.5, 
                                   central_latitude=38.5, 
                                   standard_parallels=(38.5, 38.5),
                                    globe=ccrs.Globe(semimajor_axis=6371229,
                                                     semiminor_axis=6371229))

x, y = projection.transform_point(point_lon, point_lat, ccrs.PlateCarree())

nearest_point = chunk_index.sel(x=x, y=y, method="nearest")
fcst_chunk_id = f"0.{nearest_point.chunk_id.values}"
print(fcst_chunk_id)

0.4.10


In [30]:
%%time
def retrieve_data(s3_url):
    with fs.open(s3_url, 'rb') as compressed_data: # using s3fs
        buffer = ncd.blosc.decompress(compressed_data.read())

        dtype = "<f2"
        if "surface/PRES" in s3_url: # surface/PRES is the only variable with a larger data type
            dtype = "<f4"

        chunk = np.frombuffer(buffer, dtype=dtype)
        
        entry_size = 150*150
        num_entries = len(chunk)//entry_size

        if num_entries == 1: # analysis file is 2d
            data_array = np.reshape(chunk, (150, 150))
        else:
            data_array = np.reshape(chunk, (num_entries, 150, 150))

    return data_array


data = retrieve_data(data_url + fcst_chunk_id)

CPU times: user 48.6 ms, sys: 32.5 ms, total: 81 ms
Wall time: 51.2 s


In [31]:
gridpoint_forecast = data[:, nearest_point.in_chunk_y, nearest_point.in_chunk_x]

In [38]:
hgt = gridpoint_forecast

In [39]:
hgt

array([208.4, 214. , 211. , 215.9, 214.5, 213.1, 211.9, 215.2, 212.4,
       215.8, 219.5, 224.9, 226.8, 225. , 230.4, 231.9, 229.6, 226.8,
       220. , 218.8, 216.8, 216.2, 214.9, 214.8, 213.1, 206.8, 203.8,
       200.2, 196.1, 189. , 184.2, 182. , 177.5, 175.9, 173.5, 174. ],
      dtype=float16)

In [36]:
hgt[-9]

200.2

In [37]:
hgt[-5]

182.0